from code.responseEvaluation import evaluateMultipleResponses

context = "I am going through some things with my feelings and myself. I barely sleep and I do nothing but think about how I am worthless and how I should not be here. I have never tried or contemplated suicide. I have always wanted to fix my issues, but I never get around to it. How can I change my feeling of being worthless to everyone?"
responses = ["It is clear that you are struggling with some deep feelings of worthlessness. One step towards change is acknowledging your feelings, so well done for reaching out. Have you noticed any specific triggers or patterns that lead to these thoughts about worthlessness? Understanding triggers can help identify strategies to manage these feelings. Can you pinpoint any situations or thoughts that tend to make you feel more worthless?",
             "Feeling worthless can be incredibly overwhelming, and it's positive that you want to address these feelings. Have you considered seeking support from a mental health professional? They can provide tools and techniques to help you navigate and overcome these emotions. What do you think about the idea of working with a therapist or counselor to explore these feelings and develop coping strategies?",
             "It's tough to feel like you're not valued or worthy. One way to start changing these feelings is by challenging negative thoughts and replacing them with more positive and realistic ones. Are there any activities or hobbies that bring you a sense of purpose or joy? Is there something you used to enjoy or have always wanted to try that could bring a sense of fulfillment and purpose to your life?",
             "It sounds like these feelings of worthlessness are weighing heavily on you. Have you considered practicing self-compassion and kindness towards yourself? Sometimes, treating ourselves with the same empathy we offer others can make a significant difference. What are some ways you can show yourself kindness and compassion during difficult times?",
             "Your desire to fix these feelings is a positive step forward. Have you explored any mindfulness or relaxation techniques? Sometimes, taking a moment to ground ourselves in the present can alleviate feelings of worthlessness. Would you be open to trying some relaxation exercises or mindfulness techniques to help calm your mind and manage these feelings?"]

print("Best Response:", evaluateMultipleResponses(context, responses))